apiVersion: v1 
kind: Service
metadata:
  name: backend-numbers
spec:
  selector:
    app: backend-numbers
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-numbers
  labels:
    app: backend-numbers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-numbers
  template:
    metadata:
      labels:
        app: backend-numbers
    spec:
      containers:
      - name: backend-numbers
        image: henil13/backend-numbers
        ports:
        - containerPort: 5000