- hosts: all
  become: true
  roles:
  - install-docker

- hosts: manager
  become: true
  roles:
  - swarm-manager

- hosts: worker
  become: true
  roles:
  - swarm-worker

- hosts: nginx
  become: true
  roles:
  - nginx

