---
- name: 'Install dependencies'
  apt:
    pkg:
    - apt-transport-https 
    - ca-certificates 
    - curl 
    - gnupg 
    - lsb-release
    - python3
    - python3-pip

- name: 'Get Docker Apt Key'
  apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg
    state: present 

- name: 'Get Docker APT Repo'
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
    state: present

- name: 'Install Docker'
  apt:
    pkg:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: 'Add the user' 
  ansible.builtin.user:
    name: henil
    groups: docker
    append: yes

- name: "Install docker with pip"
  pip:
    name: docker
    executable: pip3